### ISSUE TITLE
TP1 Aprobado: 8 (Ocho)

### ISSUE THREAD

**Issue by egenender** [juanh2607/TDA-tp1#1]
El TP1 queda Aprobado: 7 (Siete)
Se aplica una reducción importante a la nota por no cumplir el requerimiento de consigna en lo relativo al programa.
El resto del trabajo es de bastante buen nivel, incluyo primero detalles que se pueden mejorar, y al final una recomendación

> def main():
>     pruebas = [
>         "20.txt",
>         "25.txt",
>         "50.txt",
>         "100.txt",
>         "1000.txt",
>         "10000.txt",
>         "20000.txt",
>     ]

Lo entregado no es un programa con la capacidad de recibir un nombre de archivo por los parámetros del programa, no cumple con la consigna.

Avisenmé si desean volver a subir el archivo main con esta corrección, para que yo les diga si el cambio fue satisfactorio, y evitar arrastrar el error a tps futuros.

> El algoritmo propuesto es de tipo Greedy porque para cada iteraci´on (en este caso, cada turno)
> estamos eligiendo la mejor opci´on posible para ese momento, sin importar lo que pas´o en el turno
> anterior ni tampoco lo que va a pasar en el turno siguiente

Lo descrito en este texto no se correlaciona de ninguna manera con ser un algoritmo Greedy.

> Ninguno ”mira a futuro”,
> es decir ninguno elige pensando en maximizar (o minimizar) su puntaje

Ojo, las elecciones de Sophia sí buscan maximizar su puntaje (óptimo global), pero sí es cierto que lo hace sin mirar a futuro.

> Nuestro estado actual no es modificado en ning´un momento

Si el estado actual fuera siempre el mismo, el algoritmo nunca terminaría

> S´olo importa el estado actual del problema,
> de modo que aplicando iterativamente nuestra regla sencilla para cada momento del problema,
> vamos a obtener el ´optimo local para cada caso y terminar llegando a obtener el ´optimo global,
> que es que Sophia obtenga la victoria

Esto es correcto

> Al aplicar la regla greedy en cada turno, le damos la ventaja
> a Sophia en todo momento, lo que le asegura ganar al final de la partida

Esto requiere ser demostrado.

> Notamos esta particularidad con los casos de empate. Si hay monedas del mismo valor a ambos
> lados del arreglo, decidir si tomamos la de la izquierda o la derecha afecta al resultado final, ya
> que cambia la moneda que es nueva opci´on en el siguiente turno

Aclarar que para el enunciado "con diferentes valores", esta situación no podría darse. Más allá de eso, el análisis propuesto es interesante.

> Si la cantidad k es impar
> Si la cantidad k es par

¿Qué es k en estos contextos? ¿Debería esto definirse en función de n?

> Caso Base: para n = 2, Sophia gana ya que, de las dos opciones, va a seleccionar la mejor en
> su primer turno, dejando sin alternativa a Matheo. Por lo tanto:

Se establece el caso base en función de la cantidad de monedas, pero:

> Paso Inductivo:

Para el paso inductivo se incrementa en 1 el valor de h, sin embargo eso le permite tanto a Sophia como a Mateo tener una nueva moneda cada uno.

La solución: el caso base se puede definir para una cantidad de respectivos turnos, y en todo caso completar la demostración con el turno extra que tiene Sophia si la cantidad de monedas es impar.

> y el segundo t´ermino tambi´en

ya que la estrategia aplicada da la moneda más grande a Sophia, y la más pequeña...

> La ´unica excepci´on es que las
> monedas son todas iguales, en ese caso la partida terminar´a en empate si hay una cantidad par de
> monedas

Es interesante mencionarlo, ya que es una variabilidad de valores que puede afectar la optimalidad.
Sin embargo, no es la única excepción, también se da en casos simétricos como 1, 2, 3, 3, 2, 1

> Variabilidad

Para todos los casos realizados, se podría mencionar si el algoritmo encontró solución en la que gane Sophia

Pueden leer en detalle los comentarios, y al final les dejo una guía para pensar en mejoras que puedan tener en cuenta para la realización de futuros trabajos.

> 2. Consideraciones
> Hemos demostrado que el algoritmo propuesto selecciona en cada iteraci´on la batalla con la
> menor relaci´on disponible entre tiempo e importancia, lo que asegura que la estrategia est´a orientada a minimizar el tiempo total ponderado de finalizaci´on.

La sección 1 es una introducción y la sección 2 arranca con una afirmación que no es cierta al punto en el que estamos en el informe. Para este punto del informe correspondería hablar de cosas que se detallarán a futuro, en tiempo futuro.

> En t´erminos de implementaci´on, elegimos el lenguaje de programaci´on Python debido a su
> flexibilidad.
> Esta implementaci´on nos permite calcular la complejidad temporal y espacial del algoritmo,
> que resulta ser O(nlogn) y O(n) respectivamente, asegurando su escalabilidad y eficiencia en la
> gesti´on de conjuntos de datos.

Estas consideraciones correspondería que estén presentes luego de dar a conocer el algoritmo y su implementación

> entonces, si tenemos que elegir las pr´oximas dos batallas podemos elegir primero la batalla j y
> luego la batalla k o primero la batalla k y luego la j:

Entiendo la motivación de analizarlo entre dos batallas. Pero luego debe analizarse qué ocurre con el resto de las batallas en función de las posibles decisiones que estamos planteando, y además ser conscientes que no son solamente dos batallas las posibles a seleccionar, son las batallas que aún faltan considerar.

> OP Tj = OP Ti + (Fi + tj ) ∗ bj (Fi + tj + tk) ∗ bk
> OP Tk = OP Ti + (Fi + tk) ∗ bk(Fi + tk + tj ) ∗ bj

En ambos casos falta un signo "+" antes del paréntesis con 3 términos

> Consideremos que la diferencia entre las listas es que ´unicamente en la batalla j y k invierten
> los valores, entonces:

En rigor se debe definir que se llama "inversión" cuando en ese hipotético resultado hay un elemento que viene después, pero tiene mejor valoración t/b.

> Consideremos que la diferencia entre las listas es que ´unicamente en la batalla j y k invierten
> los valores, entonces:

Lo primero que se necesita para complementar este análisis es mostrar por qué el resto de los términos de la sumatoria no se ven afectados por la inversión. Si bien se muestra cómo se afectan los dos intercambiados, no se está hablando de todo el resto de los términos. Si el resto de los términos fueran modificados también, no podríamos hacer este análisis.

Lo que le faltó a este planteo fue contextualizar estas dos batallas dentro de una solución con múltiples batallas, siendo que ellas deben ser contiguas. Se debe reconocer primero que nada que invertir b1 y b2 no afecta a ninguna batalla anterior, ni a ninguna posterior. Luego se puede comparar qué sucede con esos dos términos de la sumatoria.

> como FOi = FSi, entonces:

Esto sí se hizo para todas las batallas antes de las dos invertidas, pero corresponde hacerlo para todas las posteriores.
Entre las cosas a mencionar, cabe destacar que el tiempo total de finalización de las batallas es siempre el mismo, sin importar el orden. Quitando las dos batallas invertidas, a todas las demás no se les afecta su tiempo de finalización.

> llevando a que S tiene que ser igual a O siendo S la soluci´on ´optima al problema.

Sucede que esa no necesariamente es la única inversión. Lo que se llega a demostrar es que mediante sucesivas inversiones se puede llegar a nuestra solución sin empeorar el resultado, y por tanto, es óptima. Se complementa con el hecho de que en caso de empate en el ratio, la inversión no cambia el resultado.
Lo que se debe mencionar es que se parte desde una hipótetica solución óptima, y solamente aplicando inversiones que nunca pueden empeorar se llega a nuestra solución sin inversiones, por tanto óptima.

> La complejidad temporal del algoritmo es O(n log(n))

Sí, pero hay que justificar que el resto del trabajo realizado nunca supera esa complejidad.

> Impacto en los Tiempos del Algoritmo
> La variabilidad en los valores de ti y bi puede afectar los tiempos de ejecuci´on del algoritmo.
> Si hay una amplia variaci´on en los valores de ti
> , es posible que el algoritmo necesite m´as tiempo
> para ordenar las batallas seg´un su relaci´on t/b, lo que aumentar´ıa la complejidad temporal del
> algoritmo. 

Se afirma que _es posible_ que haya variabilidad que el algoritmo necesite más tiempo para ordenar las batallas.
Esto es así? La complejidad puede ser mayor que O(n log n)?

> Por otro lado, si hay una gran variabilidad en los valores de bi
> , el algoritmo puede
> ordenar r´apidamente las batallas pero puede requerir m´as tiempo para calcular el tiempo total
> ponderado debido a las diferentes importancias de las batallas.

Ese cálculo puede ser mayor a O(n)?

> La variabilidad en los valores de ti y bi tambi´en puede afectar la optimalidad del algoritmo. Si la
> variabilidad en los valores de ti es alta y el algoritmo selecciona las batallas bas´andose ´unicamente
> en la relaci´on t/b, puede que no se alcance la soluci´on ´optima

Esto es falso. ¿Qué es lo que se demostró en el inciso anterior entonces, con la demostración por inversion?

> En resumen, la variabilidad en los valores de ti y bi puede tener un impacto significativo en los
> tiempos de ejecuci´on y en la optimalidad del algoritmo propuesto. Es importante considerar esta
> variabilidad al analizar el rendimiento y la efectividad del algoritmo en diferentes escenarios.

Destaco que lo que se observó en esta sección es falso, y aún si fuera cierto se requiere mostrar en qué casos concretos se dan las situaciones que se mencionan. Diría que esta es la sección que más redujo la nota del trabajo.

> El gr´afico de las mediciones se puede observar que tiene un comportamiento O(nlog(n) distanci´andose de la recta O(n) a medida que aumenta n demostrando el car´acter no lineal de la
> complejidad temporal

También debería graficarse un función O(n log n) tal que podamos comparar sobre un mismo gráfico

Con respecto a la metodología, veo que se repite cada punto 10 veces, pero aún siento que quedó algo de ruido. A futuro se puede probar toquetear ese número para generar gráficos con menos ruido

> Las mediciones experimentales realizadas confirmaron la eficiencia y escalabilidad de nuestro
> algoritmo, mostrando una tendencia lineal en funci´on del tama˜no de la entrada.

Esto no es cierto

### A considerar para futuros tps

De la consigna.

> Debe ser claro cómo ejecutar el programa pasando por parámetro un set de datos como los que se dan de ejemplo.

En este caso, la opción no está disponible.

Las pruebas de variabilidad pueden ser teóricas, y también las esperamos empíricas. En ese sentido puede probarse que ninguna otra combinación podía dar un mejor resultado, empíricamente se hizo planteando diferentes escenarios de forma automática. Para el futuro pueden valerse de la herramienta de Backtracking si llegara a requerirse un análisis de estas características.

En cuanto a las mediciones temporales, dejo algunas recomendaciones generales:

- por cada tamaño de problema probar la ejecución aún con más corridas, a ver si disminuye el nivel de ruido
- al comparar con una curva teórica, pueden proponer otras posibles curvas teóricas como O(log n), O(n log n), O(n^2). El ajuste lineal en este caso sería mejor que con cualquier otra curva.

Saludos!

**Comment by juanh2607** [comment]
Hola, subimos las correcciones a main. Los cambios hechos están en la nueva sección "Correcciones" del informe.

Saludos!

**Comment by egenender** [comment]
TP1 Aprobado: 8 (Ocho)

> Paso Inductivo:

El paso inductivo asume cosas sobre el caso base, y que eso afecte al paso actual.
Esto no configura una prueba satisfactoria.
El paso inductivo podría darse tanto si es el turno de Sophia o es el turno de Mateo. Se debería probar para cualquiera de esos dos casos que el paso inductivo es demostrable.

Es por eso que en mi opinión, es mejor aplicar inducción no sobre la cantidad de monedas total, sino sobre la cantidad de monedas que toman tanto Mateo como Sophia. Para 10 monedas, una inducción de 5 pasos.
Para 11 monedas, es la misma inducción de 5 pasos, con un turno extra de Sophia, que se puede demostrar que solo mejora con respecto al caso de cantidad de monedas par.

Saludos
